name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Docker image to Amazon ECR
      env: 
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: simplebank  # Replace with your ECR repository name
        IMAGE_TAG: ${{ github.sha }}  # This uses the commit SHA as the image tag
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
