name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Configure AWS credentials using GitHub secrets
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change this to your AWS region if different

    # Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Build, tag, and push Docker image to Amazon ECR
    - name: Build, tag, and push Docker image to Amazon ECR
      env: 
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: simplebank  # Replace with your ECR repository name
        IMAGE_TAG: ${{ github.sha }}  # This uses the commit SHA as the image tag
      run: |
        # Build the Docker image
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        
        # Push the Docker image to Amazon ECR
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    # Deploy the Docker image (if applicable)
    # Add deployment steps here if you have a specific service to deploy to, such as AWS ECS or Kubernetes
